/******************************OSD_FUNCTION_DEFINE*****************************************/
/* 	
 *	����OSD�Ĺ��ܣ�λ�ÿ��������
*/
#include "RTD2014Project.h"

#if(_PROJECT_ID == _ID_ZQ_2775E15_INNOLUX_MV270KCA_D8B_8BIT_QHD180_VX2758A_2K_PRO_20241223)

/////////////// INPUT /////////////

#define _DEF_INPUT_P0_ITEM0       _MENU_FUN_INPUT_0
#define _DEF_INPUT_P0_ITEM1       _MENU_FUN_INPUT_1
#define _DEF_INPUT_P0_ITEM2       _MENU_FUN_INPUT_2


/////////////// AUDIO ADJUST /////////////

#define _DEF_AUDIO_P0_ITEM0       _MENU_FUN_VOLUME
#define _DEF_AUDIO_P0_ITEM1       _MENU_FUN_MUTE


/////////////// VIEW MODE /////////////

#define _DEF_VIEWMODE_P0_ITEM0     _MENU_FUN_VIEWMODE_STANDARD
#define _DEF_VIEWMODE_P0_ITEM1     _MENU_FUN_VIEWMODE_FPS
#define _DEF_VIEWMODE_P0_ITEM2     _MENU_FUN_VIEWMODE_RTS
#define _DEF_VIEWMODE_P0_ITEM3     _MENU_FUN_VIEWMODE_MOBA
#define _DEF_VIEWMODE_P0_ITEM4     _MENU_FUN_VIEWMODE_MOVIE
#define _DEF_VIEWMODE_P0_ITEM5     _MENU_FUN_VIEWMODE_WEB
#define _DEF_VIEWMODE_P0_ITEM6     _MENU_FUN_VIEWMODE_TEXT
#define _DEF_VIEWMODE_P0_ITEM7     _MENU_FUN_VIEWMODE_MAC
#define _DEF_VIEWMODE_P0_ITEM8     _MENU_FUN_VIEWMODE_MONO


/////////////// COLOR ADJUST /////////////

#define _DEF_COLOR_P0_ITEM0    _MENU_FUN_CONTRAST_BRIGHTNESS
#define _DEF_COLOR_P0_ITEM1    _MENU_FUN_SIX_AXIS
#define _DEF_COLOR_P0_ITEM2    _MENU_FUN_TEMP
#define _DEF_COLOR_P0_ITEM3    _MENU_FUN_GAMUT
#define _DEF_COLOR_P0_ITEM4    _MENU_FUN_SPACE
#define _DEF_COLOR_P0_ITEM5    _MENU_FUN_RANGE
#define _DEF_COLOR_P0_ITEM6    _MENU_FUN_HDR


/////////////// MANUAL IMAGE ADJUST /////////////


#define _DEF_MANUAL_IMAGE_P0_ITEM0         _MENU_FUN_SHARPNESS
#define _DEF_MANUAL_IMAGE_P0_ITEM1         _MENU_FUN_BLUELIGHT
#define _DEF_MANUAL_IMAGE_P0_ITEM2         _MENU_FUN_ASPECT
#define _DEF_MANUAL_IMAGE_P0_ITEM3         _MENU_FUN_OVERSCAN
#define _DEF_MANUAL_IMAGE_P0_ITEM4         _MENU_FUN_BLK_STABLE
#define _DEF_MANUAL_IMAGE_P0_ITEM5         _MENU_FUN_ADV_DCR
#define _DEF_MANUAL_IMAGE_P0_ITEM6         _MENU_FUN_RESPONSE_TIME 


/////////////// SETUP MENU /////////////


#define _DEF_SETUP_P0_ITEM0          _MENU_FUN_LANGUAGE
#define _DEF_SETUP_P0_ITEM1          _MENU_FUN_FREESYNC
#define _DEF_SETUP_P0_ITEM2          _MENU_FUN_MPRT
#define _DEF_SETUP_P0_ITEM3          _MENU_FUN_NOTICE
#define _DEF_SETUP_P0_ITEM4          _MENU_FUN_INFORMATION
#define _DEF_SETUP_P0_ITEM5          _MENU_FUN_OSD_TIMEOUT
#define _DEF_SETUP_P0_ITEM6          _MENU_FUN_OSD_BACKGROUND
#define _DEF_SETUP_P0_ITEM7          _MENU_FUN_POWER_INDICATOR
#define _DEF_SETUP_P0_ITEM8          _MENU_FUN_AUTO_POWEROFF
#define _DEF_SETUP_P0_ITEM9          _MENU_FUN_SLEEP
#define _DEF_SETUP_P0_ITEM10         _MENU_FUN_ECO
#define _DEF_SETUP_P0_ITEM11         _MENU_ARROW_DOWN

#define _DEF_SETUP_P1_ITEM0          _MENU_ARROW_UP 
#define _DEF_SETUP_P1_ITEM1          _MENU_FUN_DP_VERSION
#define _DEF_SETUP_P1_ITEM2          _MENU_FUN_SEARCH
#define _DEF_SETUP_P1_ITEM3          _MENU_FUN_DDCCI
#define _DEF_SETUP_P1_ITEM4          _MENU_FUN_RECALL


#elif(_PROJECT_ID==_ID_ZQ_2775E15_BOE_DV245QHB_N20_8BIT_QHD180_ZQ25F180_20250110 || _PROJECT_ID==_ID_ZQ_2557E02_SG2701B08_4_FHD200_MKF27F240L_20250515)

/////////////// INPUT /////////////

#define _DEF_INPUT_P0_ITEM0       _MENU_FUN_INPUT_0
#define _DEF_INPUT_P0_ITEM1       _MENU_FUN_INPUT_1
#define _DEF_INPUT_P0_ITEM2       _MENU_FUN_INPUT_2


/////////////// AUDIO /////////////

#define _DEF_AUDIO_P0_ITEM0       _MENU_FUN_VOLUME
#define _DEF_AUDIO_P0_ITEM1       _MENU_FUN_MUTE


/////////////// VIEWMODE /////////////

#define _DEF_VIEWMODE_P0_ITEM0     _MENU_FUN_VIEWMODE_STANDARD
#define _DEF_VIEWMODE_P0_ITEM1     _MENU_FUN_VIEWMODE_FPS
#define _DEF_VIEWMODE_P0_ITEM2     _MENU_FUN_VIEWMODE_RTS
#define _DEF_VIEWMODE_P0_ITEM3     _MENU_FUN_VIEWMODE_MOBA
#define _DEF_VIEWMODE_P0_ITEM4     _MENU_FUN_VIEWMODE_MOVIE
#define _DEF_VIEWMODE_P0_ITEM5     _MENU_FUN_VIEWMODE_WEB
#define _DEF_VIEWMODE_P0_ITEM6     _MENU_FUN_VIEWMODE_TEXT

#define _DEF_VIEWMODE_P1_ITEM0     _MENU_FUN_VIEWMODE_MONO


/////////////// COLOR /////////////

#define _DEF_COLOR_P0_ITEM0    _MENU_FUN_CONTRAST_BRIGHTNESS
#define _DEF_COLOR_P0_ITEM1    _MENU_FUN_SIX_AXIS
#define _DEF_COLOR_P0_ITEM2    _MENU_FUN_TEMP
#define _DEF_COLOR_P0_ITEM3    _MENU_FUN_GAMUT
#define _DEF_COLOR_P0_ITEM4    _MENU_FUN_SPACE
#define _DEF_COLOR_P0_ITEM5    _MENU_FUN_RANGE
#define _DEF_COLOR_P0_ITEM6    _MENU_FUN_HDR


/////////////// MANUAL_IMAGE /////////////


#define _DEF_MANUAL_IMAGE_P0_ITEM0         _MENU_FUN_SHARPNESS 
#define _DEF_MANUAL_IMAGE_P0_ITEM1         _MENU_FUN_BLUELIGHT 
#define _DEF_MANUAL_IMAGE_P0_ITEM2         _MENU_FUN_ASPECT 
#define _DEF_MANUAL_IMAGE_P0_ITEM3         _MENU_FUN_OVERSCAN 
#define _DEF_MANUAL_IMAGE_P0_ITEM4         _MENU_FUN_BLK_STABLE 
#define _DEF_MANUAL_IMAGE_P0_ITEM5         _MENU_FUN_ADV_DCR 
#define _DEF_MANUAL_IMAGE_P0_ITEM6         _MENU_FUN_RESPONSE_TIME

/////////////// SETUP /////////////


#define _DEF_SETUP_P0_ITEM0          _MENU_FUN_LANGUAGE
#define _DEF_SETUP_P0_ITEM1          _MENU_FUN_FREESYNC
#define _DEF_SETUP_P0_ITEM2          _MENU_FUN_GAMING
#define _DEF_SETUP_P0_ITEM3          _MENU_FUN_NOTICE
#define _DEF_SETUP_P0_ITEM4          _MENU_FUN_INFORMATION
#define _DEF_SETUP_P0_ITEM5          _MENU_FUN_OSD_TIMEOUT
#define _DEF_SETUP_P0_ITEM6          _MENU_FUN_OSD_BACKGROUND

#define _DEF_SETUP_P1_ITEM0          _MENU_FUN_POWER_INDICATOR 
#define _DEF_SETUP_P1_ITEM1          _MENU_FUN_AUTO_POWEROFF
#define _DEF_SETUP_P1_ITEM2          _MENU_FUN_SLEEP
#define _DEF_SETUP_P1_ITEM3          _MENU_FUN_ECO
#define _DEF_SETUP_P1_ITEM4          _MENU_FUN_DP_VERSION
#define _DEF_SETUP_P1_ITEM5          _MENU_FUN_SEARCH
#define _DEF_SETUP_P1_ITEM6          _MENU_FUN_DDCCI

#define _DEF_SETUP_P2_ITEM0          _MENU_FUN_RECALL 
////////////////////////////////////////****************************//////////////////////////////////////////////////////
#elif (_PROJECT_ID==_ID_JX_2557E02_MV238FHB_NF5_QHD144_EYEPROTECT_CLASSIC_R5KEY)

/////////////// INPUT /////////////

#define _DEF_INPUT_P0_ITEM0       _MENU_FUN_INPUT_0
#define _DEF_INPUT_P0_ITEM1       _MENU_FUN_INPUT_1
#define _DEF_INPUT_P0_ITEM2       _MENU_FUN_INPUT_2


/////////////// AUDIO /////////////

#define _DEF_AUDIO_P0_ITEM0       _MENU_FUN_VOLUME
#define _DEF_AUDIO_P0_ITEM1       _MENU_FUN_MUTE


/////////////// VIEWMODE /////////////

#define _DEF_VIEWMODE_P0_ITEM0     _MENU_FUN_VIEWMODE_STANDARD
#define _DEF_VIEWMODE_P0_ITEM1     _MENU_FUN_VIEWMODE_FPS
#define _DEF_VIEWMODE_P0_ITEM2     _MENU_FUN_VIEWMODE_RTS
#define _DEF_VIEWMODE_P0_ITEM3     _MENU_FUN_VIEWMODE_MOBA
#define _DEF_VIEWMODE_P0_ITEM4     _MENU_FUN_VIEWMODE_MOVIE
#define _DEF_VIEWMODE_P0_ITEM5     _MENU_FUN_VIEWMODE_WEB
#define _DEF_VIEWMODE_P0_ITEM6     _MENU_FUN_VIEWMODE_TEXT

#define _DEF_VIEWMODE_P1_ITEM0     _MENU_FUN_VIEWMODE_MONO


/////////////// COLOR /////////////

#define _DEF_COLOR_P0_ITEM0    _MENU_FUN_CONTRAST_BRIGHTNESS
#define _DEF_COLOR_P0_ITEM1    _MENU_FUN_SIX_AXIS
#define _DEF_COLOR_P0_ITEM2    _MENU_FUN_TEMP
#define _DEF_COLOR_P0_ITEM3    _MENU_FUN_GAMUT
#define _DEF_COLOR_P0_ITEM4    _MENU_FUN_SPACE
#define _DEF_COLOR_P0_ITEM5    _MENU_FUN_RANGE
#define _DEF_COLOR_P0_ITEM6    _MENU_FUN_HDR


/////////////// MANUAL_IMAGE /////////////


#define _DEF_MANUAL_IMAGE_P0_ITEM0         _MENU_FUN_SHARPNESS 
#define _DEF_MANUAL_IMAGE_P0_ITEM1         _MENU_FUN_BLUELIGHT 
#define _DEF_MANUAL_IMAGE_P0_ITEM2         _MENU_FUN_ASPECT 
#define _DEF_MANUAL_IMAGE_P0_ITEM3         _MENU_FUN_OVERSCAN 
#define _DEF_MANUAL_IMAGE_P0_ITEM4         _MENU_FUN_BLK_STABLE 
#define _DEF_MANUAL_IMAGE_P0_ITEM5         _MENU_FUN_ADV_DCR 
#define _DEF_MANUAL_IMAGE_P0_ITEM6         _MENU_FUN_RESPONSE_TIME

/////////////// SETUP /////////////


#define _DEF_SETUP_P0_ITEM0          _MENU_FUN_LANGUAGE
#define _DEF_SETUP_P0_ITEM1          _MENU_FUN_FREESYNC
#define _DEF_SETUP_P0_ITEM2          _MENU_FUN_GAMING
#define _DEF_SETUP_P0_ITEM3          _MENU_FUN_NOTICE
#define _DEF_SETUP_P0_ITEM4          _MENU_FUN_INFORMATION
#define _DEF_SETUP_P0_ITEM5          _MENU_FUN_OSD_TIMEOUT
#define _DEF_SETUP_P0_ITEM6          _MENU_FUN_OSD_BACKGROUND

#define _DEF_SETUP_P1_ITEM0          _MENU_FUN_POWER_INDICATOR 
#define _DEF_SETUP_P1_ITEM1          _MENU_FUN_AUTO_POWEROFF
#define _DEF_SETUP_P1_ITEM2          _MENU_FUN_SLEEP
#define _DEF_SETUP_P1_ITEM3          _MENU_FUN_ECO
#define _DEF_SETUP_P1_ITEM4          _MENU_FUN_DP_VERSION
#define _DEF_SETUP_P1_ITEM5          _MENU_FUN_SEARCH
#define _DEF_SETUP_P1_ITEM6          _MENU_FUN_DDCCI

#if(_AI_EYE_PROTECTION == _ON)
#define _DEF_SETUP_P2_ITEM0          _MENU_FUN_AI_EYE_PROTECTION
#else
#define _DEF_SETUP_P2_ITEM0          _MENU_FUN_RECALL
#endif
#if(_AI_LIGHT_ADAPTIVATION == _ON)
#define _DEF_SETUP_P2_ITEM1          _MENU_FUN_AI_LIGHT_ADAPTIVATION
#endif
#if(_AI_LOW_POWER == _ON)
#define _DEF_SETUP_P2_ITEM2          _MENU_FUN_AI_LOW_POWER
#endif
#define _DEF_SETUP_P2_ITEM3          _MENU_FUN_RECALL
#elif ((_PROJECT_ID ==_ID_ZQ_2775E15_INNOLUX_MV270KCA_D8B_8BIT_QHD180_VX2758A_2K_PRO_2_20250103)||(_PROJECT_ID ==_ID_ZQ_2775E15_INNOLUX_MV270KCA_E8B_8BIT_QHD180_VX2758A_2K_PRO_2_20250228))

/////////////// INPUT /////////////

#define _DEF_INPUT_P0_ITEM0       _MENU_FUN_INPUT_0
#define _DEF_INPUT_P0_ITEM1       _MENU_FUN_INPUT_1
#define _DEF_INPUT_P0_ITEM2       _MENU_FUN_INPUT_2


/////////////// AUDIO /////////////

#define _DEF_AUDIO_P0_ITEM0       _MENU_FUN_VOLUME
#define _DEF_AUDIO_P0_ITEM1       _MENU_FUN_MUTE


/////////////// VIEWMODE /////////////

#define _DEF_VIEWMODE_P0_ITEM0     _MENU_FUN_VIEWMODE_STANDARD
#define _DEF_VIEWMODE_P0_ITEM1     _MENU_FUN_VIEWMODE_FPS
#define _DEF_VIEWMODE_P0_ITEM2     _MENU_FUN_VIEWMODE_RTS
#define _DEF_VIEWMODE_P0_ITEM3     _MENU_FUN_VIEWMODE_MOBA
#define _DEF_VIEWMODE_P0_ITEM4     _MENU_FUN_VIEWMODE_MOVIE
#define _DEF_VIEWMODE_P0_ITEM5     _MENU_FUN_VIEWMODE_WEB
#define _DEF_VIEWMODE_P0_ITEM6     _MENU_FUN_VIEWMODE_TEXT
#define _DEF_VIEWMODE_P0_ITEM7     _MENU_FUN_VIEWMODE_MAC
#define _DEF_VIEWMODE_P0_ITEM8     _MENU_FUN_VIEWMODE_MONO


/////////////// COLOR /////////////

#define _DEF_COLOR_P0_ITEM0    _MENU_FUN_CONTRAST_BRIGHTNESS
#define _DEF_COLOR_P0_ITEM1    _MENU_FUN_SIX_AXIS
#define _DEF_COLOR_P0_ITEM2    _MENU_FUN_TEMP
#define _DEF_COLOR_P0_ITEM3    _MENU_FUN_GAMUT
#define _DEF_COLOR_P0_ITEM4    _MENU_FUN_SPACE
#define _DEF_COLOR_P0_ITEM5    _MENU_FUN_RANGE
#define _DEF_COLOR_P0_ITEM6    _MENU_FUN_HDR


/////////////// MANUAL_IMAGE /////////////


#define _DEF_MANUAL_IMAGE_P0_ITEM0         _MENU_FUN_SHARPNESS 
#define _DEF_MANUAL_IMAGE_P0_ITEM1         _MENU_FUN_BLUELIGHT 
#define _DEF_MANUAL_IMAGE_P0_ITEM2         _MENU_FUN_ASPECT 
#define _DEF_MANUAL_IMAGE_P0_ITEM3         _MENU_FUN_OVERSCAN 
#define _DEF_MANUAL_IMAGE_P0_ITEM4         _MENU_FUN_BLK_STABLE 
#define _DEF_MANUAL_IMAGE_P0_ITEM5         _MENU_FUN_ADV_DCR 
#define _DEF_MANUAL_IMAGE_P0_ITEM6         _MENU_FUN_RESPONSE_TIME 


/////////////// SETUP /////////////


#define _DEF_SETUP_P0_ITEM0          _MENU_FUN_LANGUAGE
#define _DEF_SETUP_P0_ITEM1          _MENU_FUN_FREESYNC
#define _DEF_SETUP_P0_ITEM2          _MENU_FUN_MPRT
#define _DEF_SETUP_P0_ITEM3          _MENU_FUN_NOTICE
#define _DEF_SETUP_P0_ITEM4          _MENU_FUN_INFORMATION
#define _DEF_SETUP_P0_ITEM5          _MENU_FUN_OSD_TIMEOUT
#define _DEF_SETUP_P0_ITEM6          _MENU_FUN_OSD_BACKGROUND
#define _DEF_SETUP_P0_ITEM7          _MENU_FUN_OSD_PIVOT
#define _PIVOT_INDEX                    7
#define _DEF_SETUP_P0_ITEM8          _MENU_FUN_POWER_INDICATOR
#define _DEF_SETUP_P0_ITEM9          _MENU_FUN_AUTO_POWEROFF
#define _DEF_SETUP_P0_ITEM10         _MENU_FUN_SLEEP
#define _DEF_SETUP_P0_ITEM11         _MENU_ARROW_DOWN 

#define _DEF_SETUP_P1_ITEM0          _MENU_ARROW_UP 
#define _DEF_SETUP_P1_ITEM1          _MENU_FUN_ECO
#define _DEF_SETUP_P1_ITEM2          _MENU_FUN_DP_VERSION
#define _DEF_SETUP_P1_ITEM3          _MENU_FUN_SEARCH
#define _DEF_SETUP_P1_ITEM4          _MENU_FUN_DDCCI
#define _DEF_SETUP_P1_ITEM5          _MENU_FUN_RECALL



////////////////////////////////////////****************************//////////////////////////////////////////////////////

#elif(_PROJECT_ID ==_ID_ZQ_2775E15_INNOLUX_MV270KCA_D8B_8BIT_QHD180_VX2756_2K_PRO_2_20250115)

/////////////// INPUT /////////////

#define _DEF_INPUT_P0_ITEM0       _MENU_FUN_INPUT_0
#define _DEF_INPUT_P0_ITEM1       _MENU_FUN_INPUT_1
#define _DEF_INPUT_P0_ITEM2       _MENU_FUN_INPUT_2


/////////////// AUDIO /////////////

#define _DEF_AUDIO_P0_ITEM0       _MENU_FUN_VOLUME
#define _DEF_AUDIO_P0_ITEM1       _MENU_FUN_MUTE


/////////////// VIEWMODE /////////////

#define _DEF_VIEWMODE_P0_ITEM0     _MENU_FUN_VIEWMODE_STANDARD
#define _DEF_VIEWMODE_P0_ITEM1     _MENU_FUN_VIEWMODE_FPS
#define _DEF_VIEWMODE_P0_ITEM2     _MENU_FUN_VIEWMODE_RTS
#define _DEF_VIEWMODE_P0_ITEM3     _MENU_FUN_VIEWMODE_MOBA
#define _DEF_VIEWMODE_P0_ITEM4     _MENU_FUN_VIEWMODE_MOVIE
#define _DEF_VIEWMODE_P0_ITEM5     _MENU_FUN_VIEWMODE_WEB
#define _DEF_VIEWMODE_P0_ITEM6     _MENU_FUN_VIEWMODE_TEXT
#define _DEF_VIEWMODE_P0_ITEM7     _MENU_FUN_VIEWMODE_MAC
#define _DEF_VIEWMODE_P0_ITEM8     _MENU_FUN_VIEWMODE_MONO


/////////////// COLOR /////////////

#define _DEF_COLOR_P0_ITEM0    _MENU_FUN_CONTRAST_BRIGHTNESS
#define _DEF_COLOR_P0_ITEM1    _MENU_FUN_SIX_AXIS
#define _DEF_COLOR_P0_ITEM2    _MENU_FUN_TEMP
#define _DEF_COLOR_P0_ITEM3    _MENU_FUN_SPACE
#define _DEF_COLOR_P0_ITEM4    _MENU_FUN_RANGE
#define _DEF_COLOR_P0_ITEM5    _MENU_FUN_HDR


/////////////// MANUAL_IMAGE /////////////


#define _DEF_MANUAL_IMAGE_P0_ITEM0         _MENU_FUN_SHARPNESS 
#define _DEF_MANUAL_IMAGE_P0_ITEM1         _MENU_FUN_BLUELIGHT 
#define _DEF_MANUAL_IMAGE_P0_ITEM2         _MENU_FUN_ASPECT 
#define _DEF_MANUAL_IMAGE_P0_ITEM3         _MENU_FUN_OVERSCAN 
#define _DEF_MANUAL_IMAGE_P0_ITEM4         _MENU_FUN_BLK_STABLE 
#define _DEF_MANUAL_IMAGE_P0_ITEM5         _MENU_FUN_ADV_DCR 
#define _DEF_MANUAL_IMAGE_P0_ITEM6         _MENU_FUN_RESPONSE_TIME 


/////////////// PIP PBP /////////////


#define _DEF_SETUP_P0_ITEM0          _MENU_FUN_LANGUAGE
#define _DEF_SETUP_P0_ITEM1          _MENU_FUN_FREESYNC
#define _DEF_SETUP_P0_ITEM2          _MENU_FUN_NOTICE
#define _DEF_SETUP_P0_ITEM3          _MENU_FUN_INFORMATION
#define _DEF_SETUP_P0_ITEM4          _MENU_FUN_OSD_TIMEOUT
#define _DEF_SETUP_P0_ITEM5          _MENU_FUN_OSD_BACKGROUND
#define _DEF_SETUP_P0_ITEM6          _MENU_FUN_POWER_INDICATOR
#define _DEF_SETUP_P0_ITEM7          _MENU_FUN_AUTO_POWEROFF
#define _DEF_SETUP_P0_ITEM8          _MENU_FUN_SLEEP
#define _DEF_SETUP_P0_ITEM9          _MENU_FUN_ECO
#define _DEF_SETUP_P0_ITEM10          _MENU_FUN_DP_VERSION
#define _DEF_SETUP_P0_ITEM11         _MENU_FUN_SEARCH
#define _DEF_SETUP_P0_ITEM12         _MENU_ARROW_DOWN 

#define _DEF_SETUP_P1_ITEM0          _MENU_ARROW_UP 
#define _DEF_SETUP_P1_ITEM1          _MENU_FUN_DDCCI
#define _DEF_SETUP_P1_ITEM2          _MENU_FUN_RECALL



////////////////////////////////////////****************************//////////////////////////////////////////////////////

#elif(_PROJECT_ID ==_ID_ZQ_2775E15_BOE_ME270QHB_NF2_8BIT_QHD180_VX2756_2K_PRO_2_20250224)

/////////////// INPUT /////////////

#define _DEF_INPUT_P0_ITEM0       _MENU_FUN_INPUT_0
#define _DEF_INPUT_P0_ITEM1       _MENU_FUN_INPUT_1
#define _DEF_INPUT_P0_ITEM2       _MENU_FUN_INPUT_2


/////////////// AUDIO /////////////

#define _DEF_AUDIO_P0_ITEM0       _MENU_FUN_VOLUME
#define _DEF_AUDIO_P0_ITEM1       _MENU_FUN_MUTE


/////////////// VIEWMODE /////////////

#define _DEF_VIEWMODE_P0_ITEM0     _MENU_FUN_VIEWMODE_STANDARD
#define _DEF_VIEWMODE_P0_ITEM1     _MENU_FUN_VIEWMODE_FPS
#define _DEF_VIEWMODE_P0_ITEM2     _MENU_FUN_VIEWMODE_RTS
#define _DEF_VIEWMODE_P0_ITEM3     _MENU_FUN_VIEWMODE_MOBA
#define _DEF_VIEWMODE_P0_ITEM4     _MENU_FUN_VIEWMODE_MOVIE
#define _DEF_VIEWMODE_P0_ITEM5     _MENU_FUN_VIEWMODE_WEB
#define _DEF_VIEWMODE_P0_ITEM6     _MENU_FUN_VIEWMODE_TEXT
#define _DEF_VIEWMODE_P0_ITEM7     _MENU_FUN_VIEWMODE_MAC
#define _DEF_VIEWMODE_P0_ITEM8     _MENU_FUN_VIEWMODE_MONO


/////////////// COLOR /////////////

#define _DEF_COLOR_P0_ITEM0    _MENU_FUN_CONTRAST_BRIGHTNESS
#define _DEF_COLOR_P0_ITEM1    _MENU_FUN_SIX_AXIS
#define _DEF_COLOR_P0_ITEM2    _MENU_FUN_TEMP
#define _DEF_COLOR_P0_ITEM3    _MENU_FUN_SPACE
#define _DEF_COLOR_P0_ITEM4    _MENU_FUN_RANGE
#define _DEF_COLOR_P0_ITEM5    _MENU_FUN_HDR


/////////////// MANUAL_IMAGE /////////////


#define _DEF_MANUAL_IMAGE_P0_ITEM0         _MENU_FUN_SHARPNESS 
#define _DEF_MANUAL_IMAGE_P0_ITEM1         _MENU_FUN_BLUELIGHT 
#define _DEF_MANUAL_IMAGE_P0_ITEM2         _MENU_FUN_ASPECT 
#define _DEF_MANUAL_IMAGE_P0_ITEM3         _MENU_FUN_OVERSCAN 
#define _DEF_MANUAL_IMAGE_P0_ITEM4         _MENU_FUN_BLK_STABLE 
#define _DEF_MANUAL_IMAGE_P0_ITEM5         _MENU_FUN_ADV_DCR 
#define _DEF_MANUAL_IMAGE_P0_ITEM6         _MENU_FUN_RESPONSE_TIME 


/////////////// PIP PBP /////////////


#define _DEF_SETUP_P0_ITEM0          _MENU_FUN_LANGUAGE
#define _DEF_SETUP_P0_ITEM1          _MENU_FUN_FREESYNC
#define _DEF_SETUP_P0_ITEM2          _MENU_FUN_NOTICE
#define _DEF_SETUP_P0_ITEM3          _MENU_FUN_INFORMATION
#define _DEF_SETUP_P0_ITEM4          _MENU_FUN_OSD_TIMEOUT
#define _DEF_SETUP_P0_ITEM5          _MENU_FUN_OSD_BACKGROUND
#define _DEF_SETUP_P0_ITEM6          _MENU_FUN_POWER_INDICATOR
#define _DEF_SETUP_P0_ITEM7          _MENU_FUN_AUTO_POWEROFF
#define _DEF_SETUP_P0_ITEM8          _MENU_FUN_SLEEP
#define _DEF_SETUP_P0_ITEM9          _MENU_FUN_ECO
#define _DEF_SETUP_P0_ITEM10          _MENU_FUN_DP_VERSION
#define _DEF_SETUP_P0_ITEM11         _MENU_FUN_SEARCH
#define _DEF_SETUP_P0_ITEM12         _MENU_ARROW_DOWN 

#define _DEF_SETUP_P1_ITEM0          _MENU_ARROW_UP 
#define _DEF_SETUP_P1_ITEM1          _MENU_FUN_DDCCI
#define _DEF_SETUP_P1_ITEM2          _MENU_FUN_RECALL


#elif(_PROJECT_ID==_ID_ZQ_2513E05_PANDA_LC215DTBA_8BIT_FHD75_VA2271_H_20241223)

//�ź�Դ
#define _DEF_INPUT_P0_ITEM0       _MENU_FUN_INPUT_0
#define _DEF_INPUT_P0_ITEM1       _MENU_FUN_INPUT_2//_MENU_FUN_INPUT_1


//��Ƶ����
#define _DEF_AUDIO_P0_ITEM0       _MENU_FUN_VOLUME
#define _DEF_AUDIO_P0_ITEM1       _MENU_NULL

//Ӱ���У
#define _DEF_VIEWMODE_P0_ITEM0     _MENU_FUN_VIEWMODE_STANDARD
#define _DEF_VIEWMODE_P0_ITEM1     _MENU_FUN_VIEWMODE_FPS
#define _DEF_VIEWMODE_P0_ITEM2     _MENU_FUN_VIEWMODE_RTS
#define _DEF_VIEWMODE_P0_ITEM3     _MENU_FUN_VIEWMODE_MOBA
#define _DEF_VIEWMODE_P0_ITEM4     _MENU_FUN_VIEWMODE_MOVIE
#define _DEF_VIEWMODE_P0_ITEM5     _MENU_FUN_VIEWMODE_WEB
#define _DEF_VIEWMODE_P0_ITEM6     _MENU_FUN_VIEWMODE_TEXT
#define _DEF_VIEWMODE_P0_ITEM7     _MENU_FUN_VIEWMODE_MAC
#define _DEF_VIEWMODE_P0_ITEM8     _MENU_FUN_VIEWMODE_MONO

//ɫ�ʵ���

#define _DEF_COLOR_P0_ITEM0    _MENU_FUN_CONTRAST_BRIGHTNESS
#define _DEF_COLOR_P0_ITEM1    _MENU_FUN_TEMP//_MENU_FUN_SIX_AXIS
#define _DEF_COLOR_P0_ITEM2    _MENU_FUN_SPACE//_MENU_FUN_TEMP
#define _DEF_COLOR_P0_ITEM3    _MENU_FUN_RANGE//_MENU_FUN_GAMUT


//ͼ���ֶ�����

#define _DEF_MANUAL_IMAGE_P0_ITEM0         _MENU_FUN_AUTO_IMAGE_ADJ//_MENU_FUN_SHARPNESS 
#define _DEF_MANUAL_IMAGE_P0_ITEM1         _MENU_FUN_HORIZONTAL_SIZE//_MENU_FUN_BLUELIGHT 
#define _DEF_MANUAL_IMAGE_P0_ITEM2         _MENU_FUN_VGA_POSTION//_MENU_FUN_ASPECT 
#define _DEF_MANUAL_IMAGE_P0_ITEM3         _MENU_FUN_FINE_TUNE//_MENU_FUN_OVERSCAN 
#define _DEF_MANUAL_IMAGE_P0_ITEM4         _MENU_FUN_SHARPNESS//_MENU_FUN_BLK_STABLE 
#define _DEF_MANUAL_IMAGE_P0_ITEM5         _MENU_FUN_BLUELIGHT//_MENU_FUN_ADV_DCR 
#define _DEF_MANUAL_IMAGE_P0_ITEM6         _MENU_FUN_ASPECT//_MENU_FUN_RESPONSE_TIME 
#define _DEF_MANUAL_IMAGE_P0_ITEM7         _MENU_FUN_OVERSCAN//_MENU_NULL 
#define _DEF_MANUAL_IMAGE_P0_ITEM8         _MENU_FUN_BLK_STABLE//_MENU_NULL 
#define _DEF_MANUAL_IMAGE_P0_ITEM9         _MENU_FUN_ADV_DCR//_MENU_NULL 
#define _DEF_MANUAL_IMAGE_P0_ITEM10        _MENU_NULL//_MENU_FUN_RESPONSE_TIME//_MENU_NULL 


//�趨�˵�
#define _DEF_SETUP_P0_ITEM0          _MENU_FUN_LANGUAGE
#define _DEF_SETUP_P0_ITEM1          _MENU_FUN_NOTICE
#define _DEF_SETUP_P0_ITEM2          _MENU_FUN_INFORMATION
#define _DEF_SETUP_P0_ITEM3          _MENU_FUN_OSD_TIMEOUT
#define _DEF_SETUP_P0_ITEM4          _MENU_FUN_OSD_BACKGROUND
#define _DEF_SETUP_P0_ITEM5          _MENU_FUN_POWER_INDICATOR
#define _DEF_SETUP_P0_ITEM6          _MENU_FUN_AUTO_POWEROFF
#define _DEF_SETUP_P0_ITEM7          _MENU_FUN_SLEEP
#define _DEF_SETUP_P0_ITEM8          _MENU_FUN_ECO
#define _DEF_SETUP_P0_ITEM9          _MENU_FUN_SEARCH
#define _DEF_SETUP_P0_ITEM10         _MENU_FUN_DDCCI
#define _DEF_SETUP_P0_ITEM11         _MENU_ARROW_DOWN 
#define _DEF_SETUP_P1_ITEM0          _MENU_ARROW_UP
#define _DEF_SETUP_P1_ITEM1          _MENU_FUN_RECALL
         
#elif(_PROJECT_ID==_ID_ZQ_2513E05_BOE_HV320FHB_F4A_8BIT_FHD75_VA2271_H_20250301)

//�ź�Դ
#define _DEF_INPUT_P0_ITEM0       _MENU_FUN_INPUT_0
#define _DEF_INPUT_P0_ITEM1       _MENU_FUN_INPUT_2//_MENU_FUN_INPUT_1


//��Ƶ����
#define _DEF_AUDIO_P0_ITEM0       _MENU_FUN_VOLUME
#define _DEF_AUDIO_P0_ITEM1       _MENU_NULL

//Ӱ���У
#define _DEF_VIEWMODE_P0_ITEM0     _MENU_FUN_VIEWMODE_STANDARD
#define _DEF_VIEWMODE_P0_ITEM1     _MENU_FUN_VIEWMODE_FPS
#define _DEF_VIEWMODE_P0_ITEM2     _MENU_FUN_VIEWMODE_RTS
#define _DEF_VIEWMODE_P0_ITEM3     _MENU_FUN_VIEWMODE_MOBA
#define _DEF_VIEWMODE_P0_ITEM4     _MENU_FUN_VIEWMODE_MOVIE
#define _DEF_VIEWMODE_P0_ITEM5     _MENU_FUN_VIEWMODE_WEB
#define _DEF_VIEWMODE_P0_ITEM6     _MENU_FUN_VIEWMODE_TEXT
#define _DEF_VIEWMODE_P0_ITEM7     _MENU_FUN_VIEWMODE_MAC
#define _DEF_VIEWMODE_P0_ITEM8     _MENU_FUN_VIEWMODE_MONO

//ɫ�ʵ���

#define _DEF_COLOR_P0_ITEM0    _MENU_FUN_CONTRAST_BRIGHTNESS
#define _DEF_COLOR_P0_ITEM1    _MENU_FUN_TEMP//_MENU_FUN_SIX_AXIS
#define _DEF_COLOR_P0_ITEM2    _MENU_FUN_SPACE//_MENU_FUN_TEMP
#define _DEF_COLOR_P0_ITEM3    _MENU_FUN_RANGE//_MENU_FUN_GAMUT


//ͼ���ֶ�����

#define _DEF_MANUAL_IMAGE_P0_ITEM0         _MENU_FUN_AUTO_IMAGE_ADJ//_MENU_FUN_SHARPNESS 
#define _DEF_MANUAL_IMAGE_P0_ITEM1         _MENU_FUN_HORIZONTAL_SIZE//_MENU_FUN_BLUELIGHT 
#define _DEF_MANUAL_IMAGE_P0_ITEM2         _MENU_FUN_VGA_POSTION//_MENU_FUN_ASPECT 
#define _DEF_MANUAL_IMAGE_P0_ITEM3         _MENU_FUN_FINE_TUNE//_MENU_FUN_OVERSCAN 
#define _DEF_MANUAL_IMAGE_P0_ITEM4         _MENU_FUN_SHARPNESS//_MENU_FUN_BLK_STABLE 
#define _DEF_MANUAL_IMAGE_P0_ITEM5         _MENU_FUN_BLUELIGHT//_MENU_FUN_ADV_DCR 
#define _DEF_MANUAL_IMAGE_P0_ITEM6         _MENU_FUN_ASPECT//_MENU_FUN_RESPONSE_TIME 
#define _DEF_MANUAL_IMAGE_P0_ITEM7         _MENU_FUN_OVERSCAN//_MENU_NULL 
#define _DEF_MANUAL_IMAGE_P0_ITEM8         _MENU_FUN_BLK_STABLE//_MENU_NULL 
#define _DEF_MANUAL_IMAGE_P0_ITEM9         _MENU_FUN_ADV_DCR//_MENU_NULL 
#define _DEF_MANUAL_IMAGE_P0_ITEM10        _MENU_FUN_FREESYNC//_MENU_NULL//_MENU_FUN_RESPONSE_TIME//_MENU_NULL 


//�趨�˵�
#define _DEF_SETUP_P0_ITEM0          _MENU_FUN_LANGUAGE
#define _DEF_SETUP_P0_ITEM1          _MENU_FUN_NOTICE
#define _DEF_SETUP_P0_ITEM2          _MENU_FUN_INFORMATION
#define _DEF_SETUP_P0_ITEM3          _MENU_FUN_OSD_TIMEOUT
#define _DEF_SETUP_P0_ITEM4          _MENU_FUN_OSD_BACKGROUND
#define _DEF_SETUP_P0_ITEM5          _MENU_FUN_POWER_INDICATOR
#define _DEF_SETUP_P0_ITEM6          _MENU_FUN_AUTO_POWEROFF
#define _DEF_SETUP_P0_ITEM7          _MENU_FUN_SLEEP
#define _DEF_SETUP_P0_ITEM8          _MENU_FUN_ECO
#define _DEF_SETUP_P0_ITEM9          _MENU_FUN_SEARCH
#define _DEF_SETUP_P0_ITEM10         _MENU_FUN_DDCCI
#define _DEF_SETUP_P0_ITEM11         _MENU_ARROW_DOWN 
#define _DEF_SETUP_P1_ITEM0          _MENU_ARROW_UP
#define _DEF_SETUP_P1_ITEM1          _MENU_FUN_RECALL
         
#elif(_PROJECT_ID==_ID_ZQ_2313E01_BOE_MV238FHB_N63_8BIT_FHD100_WLCD_24FH25_20250207)

//�ź�Դ
#define _DEF_INPUT_P0_ITEM0       _MENU_FUN_INPUT_0
#define _DEF_INPUT_P0_ITEM1       _MENU_FUN_INPUT_2


//��Ƶ����
#define _DEF_AUDIO_P0_ITEM0       _MENU_FUN_VOLUME
#define _DEF_AUDIO_P0_ITEM1       _MENU_FUN_MUTE

//Ӱ���У
#define _DEF_VIEWMODE_P0_ITEM0     _MENU_FUN_VIEWMODE_STANDARD
#define _DEF_VIEWMODE_P0_ITEM1     _MENU_FUN_VIEWMODE_FPS
#define _DEF_VIEWMODE_P0_ITEM2     _MENU_FUN_VIEWMODE_MOVIE
#define _DEF_VIEWMODE_P0_ITEM3     _MENU_FUN_VIEWMODE_WEB
#define _DEF_VIEWMODE_P0_ITEM4     _MENU_FUN_VIEWMODE_TEXT
#define _DEF_VIEWMODE_P0_ITEM5     _MENU_FUN_VIEWMODE_MAC
#define _DEF_VIEWMODE_P0_ITEM6     _MENU_FUN_VIEWMODE_MONO


//ɫ�ʵ���

#define _DEF_COLOR_P0_ITEM0    _MENU_FUN_CONTRAST_BRIGHTNESS
#define _DEF_COLOR_P0_ITEM1    _MENU_FUN_TEMP
#define _DEF_COLOR_P0_ITEM2    _MENU_FUN_SPACE
#define _DEF_COLOR_P0_ITEM3    _MENU_FUN_RANGE


//ͼ���ֶ�����

#define _DEF_MANUAL_IMAGE_P0_ITEM0         _MENU_FUN_AUTO_IMAGE_ADJ 
#define _DEF_MANUAL_IMAGE_P0_ITEM1         _MENU_FUN_HORIZONTAL_SIZE 
#define _DEF_MANUAL_IMAGE_P0_ITEM2         _MENU_FUN_VGA_POSTION 
#define _DEF_MANUAL_IMAGE_P0_ITEM3         _MENU_FUN_FINE_TUNE 
#define _DEF_MANUAL_IMAGE_P0_ITEM4         _MENU_FUN_SHARPNESS 
#define _DEF_MANUAL_IMAGE_P0_ITEM5         _MENU_FUN_ASPECT 
#define _DEF_MANUAL_IMAGE_P0_ITEM6         _MENU_FUN_OVERSCAN 



//�趨�˵�
#define _DEF_SETUP_P0_ITEM0          _MENU_FUN_LANGUAGE
#define _DEF_SETUP_P0_ITEM1          _MENU_FUN_FREESYNC
#define _DEF_SETUP_P0_ITEM2          _MENU_FUN_NOTICE
#define _DEF_SETUP_P0_ITEM3          _MENU_FUN_INFORMATION
#define _DEF_SETUP_P0_ITEM4          _MENU_FUN_OSD_TIMEOUT
#define _DEF_SETUP_P0_ITEM5          _MENU_FUN_OSD_BACKGROUND
#define _DEF_SETUP_P0_ITEM6          _MENU_FUN_POWER_INDICATOR
#define _DEF_SETUP_P0_ITEM7          _MENU_FUN_AUTO_POWEROFF
#define _DEF_SETUP_P0_ITEM8          _MENU_FUN_SLEEP
#define _DEF_SETUP_P0_ITEM9          _MENU_FUN_ECO
#define _DEF_SETUP_P0_ITEM10          _MENU_FUN_DDCCI
#define _DEF_SETUP_P0_ITEM11         _MENU_FUN_RECALL

#endif























/////////////// INPUT /////////////


#ifndef	_DEF_INPUT_P0_ITEM0
#define _DEF_INPUT_P0_ITEM0       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P0_ITEM1
#define _DEF_INPUT_P0_ITEM1       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P0_ITEM2
#define _DEF_INPUT_P0_ITEM2       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P0_ITEM3
#define _DEF_INPUT_P0_ITEM3       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P0_ITEM4
#define _DEF_INPUT_P0_ITEM4       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P0_ITEM5
#define _DEF_INPUT_P0_ITEM5       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P0_ITEM6
#define _DEF_INPUT_P0_ITEM6       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P0_ITEM7
#define _DEF_INPUT_P0_ITEM7       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P0_ITEM8
#define _DEF_INPUT_P0_ITEM8       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P0_ITEM9
#define _DEF_INPUT_P0_ITEM9       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P0_ITEM10
#define _DEF_INPUT_P0_ITEM10      _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P0_ITEM11
#define _DEF_INPUT_P0_ITEM11      _MENU_NULL
#endif


#ifndef	_DEF_INPUT_P1_ITEM0
#define _DEF_INPUT_P1_ITEM0       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P1_ITEM1
#define _DEF_INPUT_P1_ITEM1       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P1_ITEM2
#define _DEF_INPUT_P1_ITEM2       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P1_ITEM3
#define _DEF_INPUT_P1_ITEM3       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P1_ITEM4
#define _DEF_INPUT_P1_ITEM4       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P1_ITEM5
#define _DEF_INPUT_P1_ITEM5       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P1_ITEM6
#define _DEF_INPUT_P1_ITEM6       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P1_ITEM7
#define _DEF_INPUT_P1_ITEM7       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P1_ITEM8
#define _DEF_INPUT_P1_ITEM8       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P1_ITEM9
#define _DEF_INPUT_P1_ITEM9       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P1_ITEM10
#define _DEF_INPUT_P1_ITEM10      _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P1_ITEM11
#define _DEF_INPUT_P1_ITEM11      _MENU_NULL
#endif


#ifndef	_DEF_INPUT_P2_ITEM0
#define _DEF_INPUT_P2_ITEM0       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P2_ITEM1
#define _DEF_INPUT_P2_ITEM1       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P2_ITEM2
#define _DEF_INPUT_P2_ITEM2       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P2_ITEM3
#define _DEF_INPUT_P2_ITEM3       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P2_ITEM4
#define _DEF_INPUT_P2_ITEM4       _MENU_NULL
#endif

#ifndef	_DEF_INPUT_P2_ITEM5
#define _DEF_INPUT_P2_ITEM5       _MENU_NULL 
#endif

#ifndef	_DEF_INPUT_P2_ITEM6
#define _DEF_INPUT_P2_ITEM6       _MENU_NULL 
#endif

#ifndef	_DEF_INPUT_P2_ITEM7
#define _DEF_INPUT_P2_ITEM7       _MENU_NULL 
#endif

#ifndef	_DEF_INPUT_P2_ITEM8
#define _DEF_INPUT_P2_ITEM8       _MENU_NULL 
#endif

#ifndef	_DEF_INPUT_P2_ITEM9
#define _DEF_INPUT_P2_ITEM9       _MENU_NULL 
#endif

#ifndef	_DEF_INPUT_P2_ITEM10
#define _DEF_INPUT_P2_ITEM10       _MENU_NULL 
#endif

#ifndef	_DEF_INPUT_P2_ITEM11
#define _DEF_INPUT_P2_ITEM11       _MENU_NULL 
#endif



/////////////// AUDIO /////////////

#ifndef	_DEF_AUDIO_P0_ITEM0
#define _DEF_AUDIO_P0_ITEM0       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P0_ITEM1
#define _DEF_AUDIO_P0_ITEM1       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P0_ITEM2
#define _DEF_AUDIO_P0_ITEM2       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P0_ITEM3
#define _DEF_AUDIO_P0_ITEM3       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P0_ITEM4
#define _DEF_AUDIO_P0_ITEM4       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P0_ITEM5
#define _DEF_AUDIO_P0_ITEM5       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P0_ITEM6
#define _DEF_AUDIO_P0_ITEM6       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P0_ITEM7
#define _DEF_AUDIO_P0_ITEM7       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P0_ITEM8
#define _DEF_AUDIO_P0_ITEM8       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P0_ITEM9
#define _DEF_AUDIO_P0_ITEM9       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P0_ITEM10
#define _DEF_AUDIO_P0_ITEM10      _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P0_ITEM11
#define _DEF_AUDIO_P0_ITEM11      _MENU_NULL
#endif


#ifndef	_DEF_AUDIO_P1_ITEM0
#define _DEF_AUDIO_P1_ITEM0       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P1_ITEM1
#define _DEF_AUDIO_P1_ITEM1       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P1_ITEM2
#define _DEF_AUDIO_P1_ITEM2       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P1_ITEM3
#define _DEF_AUDIO_P1_ITEM3       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P1_ITEM4
#define _DEF_AUDIO_P1_ITEM4       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P1_ITEM5
#define _DEF_AUDIO_P1_ITEM5       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P1_ITEM6
#define _DEF_AUDIO_P1_ITEM6       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P1_ITEM7
#define _DEF_AUDIO_P1_ITEM7       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P1_ITEM8
#define _DEF_AUDIO_P1_ITEM8       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P1_ITEM9
#define _DEF_AUDIO_P1_ITEM9       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P1_ITEM10
#define _DEF_AUDIO_P1_ITEM10      _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P1_ITEM11
#define _DEF_AUDIO_P1_ITEM11      _MENU_NULL
#endif


#ifndef	_DEF_AUDIO_P2_ITEM0
#define _DEF_AUDIO_P2_ITEM0       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P2_ITEM1
#define _DEF_AUDIO_P2_ITEM1       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P2_ITEM2
#define _DEF_AUDIO_P2_ITEM2       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P2_ITEM3
#define _DEF_AUDIO_P2_ITEM3       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P2_ITEM4
#define _DEF_AUDIO_P2_ITEM4       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P2_ITEM5
#define _DEF_AUDIO_P2_ITEM5       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P2_ITEM6
#define _DEF_AUDIO_P2_ITEM6       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P2_ITEM7
#define _DEF_AUDIO_P2_ITEM7       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P2_ITEM8
#define _DEF_AUDIO_P2_ITEM8       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P2_ITEM9
#define _DEF_AUDIO_P2_ITEM9       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P2_ITEM10
#define _DEF_AUDIO_P2_ITEM10       _MENU_NULL
#endif

#ifndef	_DEF_AUDIO_P2_ITEM11
#define _DEF_AUDIO_P2_ITEM11       _MENU_NULL
#endif



/////////////// VIEWMODE /////////////

#ifndef	_DEF_VIEWMODE_P0_ITEM0
#define _DEF_VIEWMODE_P0_ITEM0     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P0_ITEM1
#define _DEF_VIEWMODE_P0_ITEM1     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P0_ITEM2
#define _DEF_VIEWMODE_P0_ITEM2     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P0_ITEM3
#define _DEF_VIEWMODE_P0_ITEM3     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P0_ITEM4
#define _DEF_VIEWMODE_P0_ITEM4     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P0_ITEM5
#define _DEF_VIEWMODE_P0_ITEM5     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P0_ITEM6
#define _DEF_VIEWMODE_P0_ITEM6     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P0_ITEM7
#define _DEF_VIEWMODE_P0_ITEM7     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P0_ITEM8
#define _DEF_VIEWMODE_P0_ITEM8     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P0_ITEM9
#define _DEF_VIEWMODE_P0_ITEM9     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P0_ITEM10
#define _DEF_VIEWMODE_P0_ITEM10    _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P0_ITEM11
#define _DEF_VIEWMODE_P0_ITEM11    _MENU_NULL
#endif


#ifndef	_DEF_VIEWMODE_P1_ITEM0
#define _DEF_VIEWMODE_P1_ITEM0     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P1_ITEM1
#define _DEF_VIEWMODE_P1_ITEM1     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P1_ITEM2
#define _DEF_VIEWMODE_P1_ITEM2     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P1_ITEM3
#define _DEF_VIEWMODE_P1_ITEM3     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P1_ITEM4
#define _DEF_VIEWMODE_P1_ITEM4     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P1_ITEM5
#define _DEF_VIEWMODE_P1_ITEM5     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P1_ITEM6
#define _DEF_VIEWMODE_P1_ITEM6     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P1_ITEM7
#define _DEF_VIEWMODE_P1_ITEM7     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P1_ITEM8
#define _DEF_VIEWMODE_P1_ITEM8     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P1_ITEM9
#define _DEF_VIEWMODE_P1_ITEM9     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P1_ITEM10
#define _DEF_VIEWMODE_P1_ITEM10    _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P1_ITEM11
#define _DEF_VIEWMODE_P1_ITEM11    _MENU_NULL
#endif


#ifndef	_DEF_VIEWMODE_P2_ITEM0
#define _DEF_VIEWMODE_P2_ITEM0     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P2_ITEM1
#define _DEF_VIEWMODE_P2_ITEM1     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P2_ITEM2
#define _DEF_VIEWMODE_P2_ITEM2     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P2_ITEM3
#define _DEF_VIEWMODE_P2_ITEM3     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P2_ITEM4
#define _DEF_VIEWMODE_P2_ITEM4     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P2_ITEM5
#define _DEF_VIEWMODE_P2_ITEM5     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P2_ITEM6
#define _DEF_VIEWMODE_P2_ITEM6     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P2_ITEM7
#define _DEF_VIEWMODE_P2_ITEM7     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P2_ITEM8
#define _DEF_VIEWMODE_P2_ITEM8     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P2_ITEM9
#define _DEF_VIEWMODE_P2_ITEM9     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P2_ITEM10
#define _DEF_VIEWMODE_P2_ITEM10     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P2_ITEM11
#define _DEF_VIEWMODE_P2_ITEM11     _MENU_NULL
#endif

#ifndef	_DEF_VIEWMODE_P2_ITEM0
#define _DEF_VIEWMODE_P2_ITEM0     _MENU_NULL
#endif


/////////////// COLOR /////////////

#ifndef	_DEF_COLOR_P0_ITEM0
#define _DEF_COLOR_P0_ITEM0    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P0_ITEM1
#define _DEF_COLOR_P0_ITEM1    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P0_ITEM2
#define _DEF_COLOR_P0_ITEM2    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P0_ITEM3
#define _DEF_COLOR_P0_ITEM3    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P0_ITEM4
#define _DEF_COLOR_P0_ITEM4    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P0_ITEM5
#define _DEF_COLOR_P0_ITEM5    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P0_ITEM6
#define _DEF_COLOR_P0_ITEM6    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P0_ITEM7
#define _DEF_COLOR_P0_ITEM7    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P0_ITEM8
#define _DEF_COLOR_P0_ITEM8    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P0_ITEM9
#define _DEF_COLOR_P0_ITEM9    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P0_ITEM10
#define _DEF_COLOR_P0_ITEM10   _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P0_ITEM11
#define _DEF_COLOR_P0_ITEM11   _MENU_NULL
#endif


#ifndef	_DEF_COLOR_P1_ITEM0
#define _DEF_COLOR_P1_ITEM0    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P1_ITEM1
#define _DEF_COLOR_P1_ITEM1    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P1_ITEM2
#define _DEF_COLOR_P1_ITEM2    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P1_ITEM3
#define _DEF_COLOR_P1_ITEM3    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P1_ITEM4
#define _DEF_COLOR_P1_ITEM4    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P1_ITEM5
#define _DEF_COLOR_P1_ITEM5    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P1_ITEM6
#define _DEF_COLOR_P1_ITEM6    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P1_ITEM7
#define _DEF_COLOR_P1_ITEM7    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P1_ITEM8
#define _DEF_COLOR_P1_ITEM8    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P1_ITEM9
#define _DEF_COLOR_P1_ITEM9    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P1_ITEM10
#define _DEF_COLOR_P1_ITEM10   _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P1_ITEM11
#define _DEF_COLOR_P1_ITEM11   _MENU_NULL
#endif


#ifndef	_DEF_COLOR_P2_ITEM0
#define _DEF_COLOR_P2_ITEM0    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P2_ITEM1
#define _DEF_COLOR_P2_ITEM1    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P2_ITEM2
#define _DEF_COLOR_P2_ITEM2    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P2_ITEM3
#define _DEF_COLOR_P2_ITEM3    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P2_ITEM4
#define _DEF_COLOR_P2_ITEM4    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P2_ITEM5
#define _DEF_COLOR_P2_ITEM5    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P2_ITEM6
#define _DEF_COLOR_P2_ITEM6    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P2_ITEM7
#define _DEF_COLOR_P2_ITEM7    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P2_ITEM8
#define _DEF_COLOR_P2_ITEM8    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P2_ITEM9
#define _DEF_COLOR_P2_ITEM9    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P2_ITEM10
#define _DEF_COLOR_P2_ITEM10    _MENU_NULL
#endif

#ifndef	_DEF_COLOR_P2_ITEM11
#define _DEF_COLOR_P2_ITEM11    _MENU_NULL
#endif



/////////////// MANUAL_IMAGE /////////////


#ifndef	_DEF_MANUAL_IMAGE_P0_ITEM0
#define _DEF_MANUAL_IMAGE_P0_ITEM0         _MENU_NULL//_MENU_FUN_SHARPNESS 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P0_ITEM1
#define _DEF_MANUAL_IMAGE_P0_ITEM1         _MENU_NULL//_MENU_FUN_BLUELIGHT 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P0_ITEM2
#define _DEF_MANUAL_IMAGE_P0_ITEM2         _MENU_NULL//_MENU_FUN_ASPECT 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P0_ITEM3
#define _DEF_MANUAL_IMAGE_P0_ITEM3         _MENU_NULL//_MENU_FUN_OVERSCAN 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P0_ITEM4
#define _DEF_MANUAL_IMAGE_P0_ITEM4         _MENU_NULL//_MENU_FUN_BLK_STABLE 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P0_ITEM5
#define _DEF_MANUAL_IMAGE_P0_ITEM5         _MENU_NULL//_MENU_FUN_ADV_DCR 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P0_ITEM6
#define _DEF_MANUAL_IMAGE_P0_ITEM6         _MENU_NULL//_MENU_FUN_RESPONSE_TIME 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P0_ITEM7
#define _DEF_MANUAL_IMAGE_P0_ITEM7         _MENU_NULL//_MENU_NULL 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P0_ITEM8
#define _DEF_MANUAL_IMAGE_P0_ITEM8         _MENU_NULL//_MENU_NULL 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P0_ITEM9
#define _DEF_MANUAL_IMAGE_P0_ITEM9         _MENU_NULL//_MENU_NULL 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P0_ITEM10
#define _DEF_MANUAL_IMAGE_P0_ITEM10        _MENU_NULL//_MENU_NULL 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P0_ITEM11
#define _DEF_MANUAL_IMAGE_P0_ITEM11        _MENU_NULL 
#endif


#ifndef	_DEF_MANUAL_IMAGE_P1_ITEM0
#define _DEF_MANUAL_IMAGE_P1_ITEM0         _MENU_NULL 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P1_ITEM1
#define _DEF_MANUAL_IMAGE_P1_ITEM1         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P1_ITEM2
#define _DEF_MANUAL_IMAGE_P1_ITEM2         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P1_ITEM3
#define _DEF_MANUAL_IMAGE_P1_ITEM3         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P1_ITEM4
#define _DEF_MANUAL_IMAGE_P1_ITEM4         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P1_ITEM5
#define _DEF_MANUAL_IMAGE_P1_ITEM5         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P1_ITEM6
#define _DEF_MANUAL_IMAGE_P1_ITEM6         _MENU_NULL 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P1_ITEM7
#define _DEF_MANUAL_IMAGE_P1_ITEM7         _MENU_NULL 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P1_ITEM8
#define _DEF_MANUAL_IMAGE_P1_ITEM8         _MENU_NULL 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P1_ITEM9
#define _DEF_MANUAL_IMAGE_P1_ITEM9         _MENU_NULL 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P1_ITEM10
#define _DEF_MANUAL_IMAGE_P1_ITEM10        _MENU_NULL 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P1_ITEM11
#define _DEF_MANUAL_IMAGE_P1_ITEM11        _MENU_NULL 
#endif

#ifndef	_DEF_MANUAL_IMAGE_P2_ITEM0
#define _DEF_MANUAL_IMAGE_P2_ITEM0         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P2_ITEM1
#define _DEF_MANUAL_IMAGE_P2_ITEM1         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P2_ITEM2
#define _DEF_MANUAL_IMAGE_P2_ITEM2         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P2_ITEM3
#define _DEF_MANUAL_IMAGE_P2_ITEM3         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P2_ITEM4
#define _DEF_MANUAL_IMAGE_P2_ITEM4         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P2_ITEM5
#define _DEF_MANUAL_IMAGE_P2_ITEM5         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P2_ITEM6
#define _DEF_MANUAL_IMAGE_P2_ITEM6         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P2_ITEM7
#define _DEF_MANUAL_IMAGE_P2_ITEM7         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P2_ITEM8
#define _DEF_MANUAL_IMAGE_P2_ITEM8         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P2_ITEM9
#define _DEF_MANUAL_IMAGE_P2_ITEM9         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P2_ITEM10
#define _DEF_MANUAL_IMAGE_P2_ITEM10         _MENU_NULL
#endif

#ifndef	_DEF_MANUAL_IMAGE_P2_ITEM11
#define _DEF_MANUAL_IMAGE_P2_ITEM11         _MENU_NULL
#endif


/////////////// SETUP /////////////


#ifndef	_DEF_SETUP_P0_ITEM0
#define _DEF_SETUP_P0_ITEM0          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P0_ITEM1
#define _DEF_SETUP_P0_ITEM1          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P0_ITEM2
#define _DEF_SETUP_P0_ITEM2          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P0_ITEM3
#define _DEF_SETUP_P0_ITEM3          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P0_ITEM4
#define _DEF_SETUP_P0_ITEM4          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P0_ITEM5
#define _DEF_SETUP_P0_ITEM5          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P0_ITEM6
#define _DEF_SETUP_P0_ITEM6          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P0_ITEM7
#define _DEF_SETUP_P0_ITEM7          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P0_ITEM8
#define _DEF_SETUP_P0_ITEM8          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P0_ITEM9
#define _DEF_SETUP_P0_ITEM9          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P0_ITEM10
#define _DEF_SETUP_P0_ITEM10         _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P0_ITEM11
#define _DEF_SETUP_P0_ITEM11         _MENU_NULL
#endif


#ifndef	_DEF_SETUP_P1_ITEM0
#define _DEF_SETUP_P1_ITEM0          _MENU_NULL 
#endif

#ifndef	_DEF_SETUP_P1_ITEM1
#define _DEF_SETUP_P1_ITEM1          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P1_ITEM2
#define _DEF_SETUP_P1_ITEM2          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P1_ITEM3
#define _DEF_SETUP_P1_ITEM3          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P1_ITEM4
#define _DEF_SETUP_P1_ITEM4          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P1_ITEM5
#define _DEF_SETUP_P1_ITEM5          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P1_ITEM6
#define _DEF_SETUP_P1_ITEM6         _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P1_ITEM7
#define _DEF_SETUP_P1_ITEM7          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P1_ITEM8
#define _DEF_SETUP_P1_ITEM8          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P1_ITEM9
#define _DEF_SETUP_P1_ITEM9          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P1_ITEM10
#define _DEF_SETUP_P1_ITEM10         _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P1_ITEM11
#define _DEF_SETUP_P1_ITEM11         _MENU_NULL
#endif


#ifndef	_DEF_SETUP_P2_ITEM0
#define _DEF_SETUP_P2_ITEM0          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P2_ITEM1
#define _DEF_SETUP_P2_ITEM1          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P2_ITEM2
#define _DEF_SETUP_P2_ITEM2          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P2_ITEM3
#define _DEF_SETUP_P2_ITEM3          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P2_ITEM4
#define _DEF_SETUP_P2_ITEM4          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P2_ITEM5
#define _DEF_SETUP_P2_ITEM5          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P2_ITEM6
#define _DEF_SETUP_P2_ITEM6          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P2_ITEM7
#define _DEF_SETUP_P2_ITEM7          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P2_ITEM8
#define _DEF_SETUP_P2_ITEM8          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P2_ITEM9
#define _DEF_SETUP_P2_ITEM9          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P2_ITEM10
#define _DEF_SETUP_P2_ITEM10          _MENU_NULL
#endif

#ifndef	_DEF_SETUP_P2_ITEM11
#define _DEF_SETUP_P2_ITEM11          _MENU_NULL
#endif




#ifndef	_PIVOT_INDEX
#define _PIVOT_INDEX                    7
#endif


